export declare const defaultStyle: string;
export declare const descriptor1: string;
export declare const h1: string;
export declare const h2: string;
export declare const h3: string;
export declare const h4: string;
export declare const h5: string;
export declare const h6: string;
export declare const text1: string;
